# Generated by Django 5.1.5 on 2025-01-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('cognom1', models.CharField(max_length=20)),
                ('cognom2', models.CharField(max_length=20)),
                ('correu', models.CharField(max_length=50)),
                ('curs', models.CharField(max_length=10)),
                ('moduls_matriculats', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('cognom', models.CharField(max_length=20)),
                ('edat', models.IntegerField(max_length=20)),
                ('rol', models.CharField(max_length=20)),
                ('curs', models.CharField(max_length=20)),
            ],
        ),
    ]
